### ISSUE TITLE
get_calibration_images works well but I can't open the shutter

### ISSUE THREAD

**Issue by chiahaoliu** [chiahaoliu/xpdAcquireFuncs#4]
@sbillinge 

get_calibration images works fine, but even after entering: caput XF:28IDC-OP:1{Fltr}Cmd:Opn4-Cmd 1
and get following feedback in command prompt:
Old : XF:28IDC-OP:1{Fltr}Cmd:Opn4-Cmd In
New : XF:28IDC-OP:1{Fltr}Cmd:Opn4-Cmd In     # I did it twice to make sure it is open
Images collected from calibration scan are dark. Not sure if that problem from my side

**Comment by chiahaoliu** [comment]
Almost confirm that can't open the shutter remotely

**Comment by sbillinge** [comment]
Let's work with Sanjit today to see if we can trouble-shoot this.

There are two issues:
1) can we run the command line function from the ipython script and have it return the result back to the script for further processing
2) what is the problem with remote opening.

We don't have to worry about (2) because it is not a real use-case (we actually don't want people controlling stuff from outside).  We _should_ test it with Sanjit sitting at the beamline though to see if we can find the problem.

However, (1) would be good to solve.  Presumably, if the code is running locally and executes this command, it will work properly.
